### ISSUE TITLE
"Did not find video"

### ISSUE THREAD

**Issue by alex-phillips** [cliveontoast/GoMoPho#1]
I'm glad someone was able to write a program to do this via command line, I've been trying to do it myself! However, it doesn't seem to be working with any of the files from my phone. I opened one of my files in a hex editor and the byte sequence your config has as the MP4 header doesn't exist in my file. Is it possible that it could be a different sequence we need to look for? I'd be happy to provide one of my files for testing if that would help.

I'm on a Pixel 2 fwiw.

**Comment by WizOfWas** [comment]
Yes I have the same problem, with pixel2 it doesn't find the video file.  I attached an example.
![mvimg_20180915_093828](https://user-images.githubusercontent.com/40749570/46385723-3b238880-c683-11e8-92b9-d112e015d7c1.jpg)

**Comment by cliveontoast** [comment]
Hi Alex and WizOfWas, thanks for trying out my application.

**Comment by cliveontoast** [comment]
> 
> 
> I'm glad someone was able to write a program to do this via command line, I've been trying to do it myself! However, it doesn't seem to be working with any of the files from my phone. I opened one of my files in a hex editor and the byte sequence your config has as the MP4 header doesn't exist in my file. Is it possible that it could be a different sequence we need to look for? I'd be happy to provide one of my files for testing if that would help.
> 
> I'm on a Pixel 2 fwiw.

Do you have a sample image I could look at? The upload would be much appreciated.

**Comment by cliveontoast** [comment]
> Yes I have the same problem, with pixel2 it doesn't find the video file. I attached an example.

Thanks for the upload. I've extracted the video on the phone, so hopefully I can work out what's going on.

May I include your snail in the test-image of the project?

**Comment by cliveontoast** [comment]
I've resolved WizOfWas image in version 1.2
I've also tried to add a better approach to search for the start of the mp4 binary format for you Alex. If it still has no success, I would appreciate your moving photo.

**Comment by cliveontoast** [comment]
> 
> 
> I'm glad someone was able to write a program to do this via command line, I've been trying to do it myself! However, it doesn't seem to be working with any of the files from my phone. I opened one of my files in a hex editor and the byte sequence your config has as the MP4 header doesn't exist in my file. Is it possible that it could be a different sequence we need to look for? I'd be happy to provide one of my files for testing if that would help.
> 
> I'm on a Pixel 2 fwiw.

Yes, I believe there is a different sequence to find. I've allowed the .config file to have as many options as desired. It's possible to add as many new keys that have the "Mp4Header_" as the start.

    <add key="Mp4Header_iso6mp42iso6avc1" value="00 00 00 20 66 74 79 70 69 73 6F 36 00 00 00 01 6D 70 34 32 69 73 6F 36 61 76 63 31 69 73 6F 6D 00 00 03"/>
    <add key="Mp4Header_mp42" value="00 00 00 18 66 74 79 70 6D 70 34 32"/>

What I know for sure, is searching for "FF D9" finds the end of the JPEG part of the file. From my reading MP4 files start with "00 00 00 " and then, from the examples from WizOfWas is then "xx 66 74 79 70" where xx has so far been either 18 or 20.

My new generic search now finds
"FF D9"
then instances of
"66 74 79 70"
then checks that "6D 70 34 32" is within the next 20 characters
then checks the four bytes prior to "66 74 79 70" are "00 00 00 xx"

Now.. explaining all that, I agree it is pretty weird, showing that I don't know the second thing about the MP4 format :)

**Comment by webvan1999** [comment]
I'm also getting "Did Not Find Video".
I know it's there though because I reuploaded up Google Photos and after some processing time it does display correctly. I've attached a file, thanks !
![MVIMG_20190508_151047](https://user-images.githubusercontent.com/30503824/57526986-27ce4f00-732f-11e9-838b-6cc92d62331b.jpg)

**Comment by juande30** [comment]
![MVIMG_20190525_115703](https://user-images.githubusercontent.com/51338003/63214921-3928b380-c0f5-11e9-95f7-926db2bf55a3.jpg)
Hi Clive, how are you? (sorry for any mistakes, english is not my primary language)

Thanks for writing this!! I'm having a problem though 😢 

I've tried the app (GoMoPhoConsole.exe) and this happens (first image is the example downloaded from here). The other files "move" on Google Photos but the mp4 part is not recognized by the app, i tried with various pics without any succses. 
I don't know how to atach a picture but here's a [LINK](https://photos.app.goo.gl/83hSVwGW6bmMnbycA) . 

Let me know if there is anything I can do to help you
Greetings from Argentina!

"
(...)
You can 1) type (or paste) in a folder now - without quotes and press <ENTER>
        2) press <ENTER> to exit


    Example typed text, afterwards pressing <ENTER>
    >c:\somewhere with spaces

> C:\Users\User\Documents\Fotos\Moving Pictures
Found the following number of google motion photos: 5
Searching C:\Users\User\Documents\Fotos\Moving Pictures\MVIMG_20180910_124410.jpg   Found the video
Searching C:\Users\User\Documents\Fotos\Moving Pictures\MVIMG_20190525_115703.jpg   Did not find video
Searching C:\Users\User\Documents\Fotos\Moving Pictures\MVIMG_20190709_171548.jpg   Did not find video
Searching C:\Users\User\Documents\Fotos\Moving Pictures\MVIMG_20190709_171551.jpg   Did not find video
Searching C:\Users\User\Documents\Fotos\Moving Pictures\MVIMG_20190816_173000.jpg   Did not find video
Finished. Processed 5 videos for 5 images files.
Press any key to exit

"

EDIT: I found how to atach a file, so obvious I missed it, sorry
