### ISSUE TITLE
no docs about MacOS

### ISSUE THREAD

**Issue by stefansegers** [cliveontoast/GoMoPho#10]
Hi, I am trying to get GoMoPho to work on the Mac. When I downloaded the Zip I got a lot of files. So I tried to make it work in Terminal "GoMoPhoCoreConsole d *.jpg"

But nothing seems to work.

Does anyone have tips how to make it work on the mac?

**Comment by cliveontoast** [comment]
Hi stefansegers,

Sorry I haven't replied earlier.

I think the fault is my poor instructions. Let me try some new ones for you.

1) Visit https://github.com/cliveontoast/GoMoPho/releases
2) Scroll down and download "GoMoPho.macOS.x.x.x.zip" where x.x.x represents the version number, currently at 2.0.4.
3) Unzip to a new folder, and run the file "GoMoPhoCoreConsole"
4) Run GoMoPhoCoreConsole - it should present with the following 

```
Welcome to google motion photos extractor.
If you provide a folder that contains google motion photos,
then I will extract any videos found
Press A to show more advanced options, otherwise press any other key to provide a folder
Please type in a directory to process motion photos and press ENTER i.e. C:\\Users\\Clive\\OneDrive\\Documents\\Pictures\\Camera Roll
>
```
5) Type in a folder with your files.. such as /Users/Martin/Pictures

**Comment by stefansegers** [comment]
Hi Clive,
thanks for your reply. I got it working. Only thing I came accros is that the movie file has the time/date of the moment it is being saved instead original date of creation. 
Is there a way to get this also working? 
This is especially handy when you combine video's and live-video's, then you can sort by date of creation. Searching through 800 files will be easier then :)

**Comment by cliveontoast** [comment]
Great tip. Sorry for the very long delay. It should certainly be possible. I'll create a new issue.
