### ISSUE TITLE
Feature Request: headless/no-prompt mode

### ISSUE THREAD

**Issue by ct-martin** [cliveontoast/GoMoPho#11]
Hello, I am trying to batch process files and not having the "press any key to exit" prompt would be really helpful for this. I am fine with a parameter for this if you don't want to remove it entirely.

**Comment by cliveontoast** [comment]
Hi @ct-martin 

Thanks for the request, what you're asking for makes perfect sense. I had the "press any key" so it just doesn't close when running from windows and double-clicking on the file..

I'll add an extra parameter

**Comment by cliveontoast** [comment]
Ok fixed in version https://github.com/cliveontoast/GoMoPho/releases/tag/v2.1.0

Add a new command line argument 

``h``
