### ISSUE TITLE
Split Command not Functioning

### ISSUE THREAD

**Issue by jonmop14** [cliveontoast/GoMoPho#12]
hi @cliveontoast  - Thanks very much for putting this together. It seems to be exactly what I'm looking for to batch remove the videos. Unfortunately, I'm not terribly technical and am getting stuck when trying to split the gif and mp4 pieces out. If i just run the extract video/no commands it works. My steps:

1. Install .NET 4.8 w/ dev apps and .NET SDK
2. Ran the Build-Test-Zip bat to create the extractor
-some Errors popped up during build, and looking back I think it was because I didnt edit the .bat, just reviewed it and ran it.
3. GoMoPhoCoreConsole.exe did get created in .\bin\netcoreapp2.0\win-64x
4. When I run the exe and just type in the directory (no arguments), it does extract the video but what I'm primarily looking for is the jpg without the mp4 and gif portion.
5. When I try to pass the split commands or try to run it all through command line, it continually asks for the directory.  See screenshot:

[https://imgur.com/a/4jhJz7c](url)
Note that i realized the directory in the first line of the screenshot is incorrect but I just tried the same steps and it still asked me to type in the directory every time.

Any help you could provide would be greatly appreciated. thank you again

**Comment by jonmop14** [comment]
![GoMoPho Message](https://user-images.githubusercontent.com/59620208/71918601-a397ca00-3150-11ea-8f20-0e8f6a32f26a.jpg)

**Comment by cliveontoast** [comment]
Hi @jonmop14 
Thanks for trying the application!

Sorry, I just fully read your message, and you have noted that the directory you have given is purposefully incorrect. I'll respond again

--- original below

Looking at the picture you've sent (thanks very much) 
I can reproduce your picture if the source directory cannot be found. 
I'm guessing the folder "F:\MVING\" does not exist. Could you try "F:\MVIMG" ?

For that part, could you type in 
``` 
GoMoPhoCoreConsole.exe d "F:\MV
```
and then press TAB 
this should then complete the folder to "F:\MVIMG" or "F:\MVING" 

Part two, the bug!
Could you remove the slash ( \\ ) at the end of "F:\MVING\Output\"

```
GoMoPhoCoreConsole.exe d "F:\MVIMG" s "e:\MVIMG\Output" g p "*.jpg"
GoMoPhoCoreConsole.exe d "F:\MVING" s "e:\MVING\Output" g p "*.jpg"
```

**Comment by cliveontoast** [comment]
Hi @jonmop14
Thanks for trying the application. 

Let me first appologise. This application was for me to experiement with creating an application compatible with both Windows and Linux/Mac, so there isn't a good user interface. I think it's about time I just create a nice interface for the windows users at least.

We can work around the issue you have discovered by not putting the final slash ( \\ ) in the paths (I found a different problem, unrelated to your screenshot)

As you don't want the gif or the video, we can simplify your work a bit by typing in the following:

```
GoMoPhoCoreConsole.exe d "F:\MVIMG
```

Notice how I've left of the trailing quote ( " ). Then press the TAB button, this should then autocomplete the folder (if it does exist) and add an extra quote. From there you can do the samefor the 's' option i.e.

```
GoMoPhoCoreConsole.exe d "F:\MVIMG"
```

If the the directory doesn't exist, you should hear an audible error sound, and no quote should appear. In this circumstance, remove a few characters and try pressing TAB again it should eventually find the folder. Failing all that type in the following

```
GoMoPhoCoreConsole.exe d "
```

- Go to windows explorer navigate to the folder
- Up the top of the window you see the path to the folder (in my computer) "This PC > SDXC (E:) > MVIMG" 
- Right click on that and choose "Edit address"
- Copy the text
- Go back to the command prompt and press CTRL+V
- -  This should then paste in the correct folder
- Pressing TAB should then add the final quote ( " )

It should look like the following
```
GoMoPhoCoreConsole.exe d "F:\MVIMG"
```

Now add the 's' option, this folder doesn't have to exist yet, but very importantly, it cannot have the trailing slash ( \\ ) !
If the folder doesn't exist yet, it should get created.

```
GoMoPhoCoreConsole.exe d "F:\MVIMG" s "F:\MVIMG\Output"

```
