### ISSUE TITLE
.NET Core 3.1 support?

### ISSUE THREAD

**Issue by JustAndreww** [cliveontoast/GoMoPho#15]
Currently universal cross-platform build giving these errors when tryin to run on Ubuntu with latest 3.1 net core:
```
dotnet ./GoMoPhoCoreConsole.dll
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - The following frameworks were found:
      3.1.7 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
``

**Comment by cliveontoast** [comment]
Thanks for the heads up about .NET Core 2.1 not being supported any more. The project is now built for .NET Core 3.1 and it is available for download https://github.com/cliveontoast/GoMoPho/releases
