### ISSUE TITLE
running on mac

### ISSUE THREAD

**Issue by pokemonbattledroid** [cliveontoast/GoMoPho#18]
Hi,
I'm having an issue or really just having a hard time figuring out how to run this on a mac.  Clearly not anywhere as clever, but would really appreciate if you are able to share a bit more detail on how to run this on the mac.  I downloaded the macOS3.1zip, but just a lot of files and unsure of what to do.  Tried a few terminal things, but I have no idea of what I'm doing...sorry!!!

**Comment by cliveontoast** [comment]
Hi gosugimoto,

Thanks for trying out the software. The initial instructions I can provide is to download .net core for the mac.

.NET runtime for MacOS https://www.microsoft.com/net/download

You should then be able to open up a terminal in the GoMoPho folder and run 

```
dotnet GoMoPhoCoreConsole.dll
```

It should give you some instructions on where to go next.

Next time I'm on a mac I'll try get some better instructions

**Comment by cliveontoast** [comment]
Others have said the mac works, so hopefully the instructions worked.
