### ISSUE TITLE
New name format

### ISSUE THREAD

**Issue by mjforan** [cliveontoast/GoMoPho#19]
Newer phones (at least the Pixel 5) have changed the naming format to PXL_date_time.MP.jpg  To get your tool to recognize these I had to prepend "MVIMG_" to each file name to match the old format.

**Comment by cliveontoast** [comment]
Hi mjforan,

Thanks for the change. Sorry for the supremely long wait for the reply. If you open the config file associated with the exe

![image](https://user-images.githubusercontent.com/35511400/119313876-a1330300-bca6-11eb-861d-2d981fd16d6b.png)

On line 4 you can change the default search pattern to the following;
```
    <add key="FilePattern" value="*.MP.jpg" />
```

**Comment by cliveontoast** [comment]
In the near future, I'll change the file pattern to a list of file patterns and add the `PXL_*.MP.jpg` pattern too. Cheers :)

**Comment by cliveontoast** [comment]
@mjforan I forgot a long while back, I added an option in the arguments of the program you can specify the pattern to search for when running the application.

`dotnet .\GoMoPhoCoreConsole.dll p "PXL*.jpg"` 

It will then ask you for the folder you wish to search

**Comment by cliveontoast** [comment]
Hi @mjforan 

Thanks for reporting the issue. I've made some updates, go [grab the lastest version](https://github.com/cliveontoast/GoMoPho/releases) and have another go
