### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by ghost** [cliveontoast/GoMoPho#2]
`dotnet ~/GoMoPho/netcoreapp2.0/GoMoPhoCoreConsole.dll`

```
Error:
  An assembly specified in the application dependencies manifest (GoMoPhoCoreConsole.deps.json) was not found:
    package: 'System.Configuration.ConfigurationManager', version: '4.5.0'
    path: 'lib/netstandard2.0/System.Configuration.ConfigurationManager.dll'
```
System: Ubuntu 18.04
installed NET according to: https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/runtime-current

**Comment by cliveontoast** [comment]
> Error:
>   An assembly specified in the application dependencies manifest (GoMoPhoCoreConsole.deps.json) was not found:
>     package: 'System.Configuration.ConfigurationManager', version: '4.5.0'
>     path: 'lib/netstandard2.0/System.Configuration.ConfigurationManager.dll'

Hi augustseptember. Thanks for the error report. I appologise that it does not work for you. I don't have a linux pc at home, but I should be able to sort something out in the office.

I'll be sure to work out what is going on yet. Not sure why it would insist on the .ConfigurationManager dll.

**Comment by cliveontoast** [comment]
Hi augustseptember, I've just released v1.2 I hope this fixes your problem. I learned a bit more about publishing dotnetcore apps using the publish feature instead.

**Comment by augustseptember** [comment]
Hi cliveontoast, thanks for your work and the answer to my issue. Unfortunately i am not familiar with this dotnet stuff and I don't know how to use your program. Could you update the readme file? In version 1.2 there is no .dll file anymore to "start", right?

**Comment by ghost** [comment]
Nice! Thank you very much! It worked very well. Though it would be nice if this program was native for linux and would come without all this Microsoft packages. :)
