### ISSUE TITLE
Pixel 7 motion pictures - did not find known video, trying generic approach - Failed to find the video out of 0 possibilites

### ISSUE THREAD

**Issue by ohadschn** [cliveontoast/GoMoPho#33]
Using the latest version at the time of writing:
https://github.com/cliveontoast/GoMoPho/releases/tag/v3.7

> GoMoPhoConsole.exe
Welcome to google motion photos extractor.
If you provide a folder that contains google motion photos,
then I will extract any videos found
Press A to show more advanced options, otherwise press any other key to provide a folder
Found the following number of google motion photos: 4
Searching C:\Users\ohad\Downloads\frames\PXL_20240721_121509046.MP.jpg   Found the video
Searching C:\Users\ohad\Downloads\frames\PXL_20240721_123647751.MP.jpg   Did not find known video, trying generic approachFailed to find the video out of 0 possibilites
Please report this output to https://github.com/cliveontoast/GoMoPho/issues and attach your moving image jpeg file
Searching C:\Users\ohad\Downloads\frames\PXL_20240721_145728784.MP.jpg   Did not find known video, trying generic approachFailed to find the video out of 0 possibilites
Please report this output to https://github.com/cliveontoast/GoMoPho/issues and attach your moving image jpeg file
Searching C:\Users\ohad\Downloads\frames\PXL_20240722_180956714.MP.jpg   Did not find known video, trying generic approachFailed to find the video out of 0 possibilites
Please report this output to https://github.com/cliveontoast/GoMoPho/issues and attach your moving image jpeg file
Finished. Processed 4 files, found 1 videos for 4 images files.
Press any key to exit

PS 
* Small nitpick 1: note how the log lines are concatenated without any separating character: `trying generic approachFailed to find`
* Small nitpick 2: typo in `possibilites`

Attached failing samples:
![PXL_20240721_145728784 MP](https://github.com/user-attachments/assets/2831e766-2efc-4417-a87e-8ac3c841978f)
![PXL_20240721_123647751 MP](https://github.com/user-attachments/assets/174f2117-1aa7-4b03-9983-f2bbc9aa835c)

For some reason, this one worked just fine, as you can see in the log (taken with the same phone, on the same day I believe):
![PXL_20240721_121509046 MP](https://github.com/user-attachments/assets/ce2c4b93-cbb6-4e88-84d3-538f5a73b1aa)

**Comment by cliveontoast** [comment]
Great photos. I'll sort something out tomorrow!

**Comment by cliveontoast** [comment]
Hi [ohadschn](https://github.com/ohadschn),

I copied the three photos to my phone. My "Google Photos" app only said the last photo was a motion photo. The other two were not.

On your phone, are all three motion photos, and are exportable to video?

Also, thanks for picking up the nit-picks. I'll put those in the next version when it appears.

**Comment by ohadschn** [comment]
Hey @cliveontoast, 

Looks like this was my bad!

All my photos are uploaded to both Google (compressed) and OneDrive (full quality).
I took these pictures from OneDrive (since I wanted the full quality) but it looks like it indeed truncates the motion part.

What misled me was the fact that the Windows Photos app did show these truncated photos as motion-enabled. When I clicked to actually show the motion it didn't work (brought up a blank screen) but I dismissed it as a Photos app bug.

So it looks like OneDrive retains the motion flag but strips off the actual video - live and learn ...

Sorry for the trouble!

**Comment by cliveontoast** [comment]
That's sad for the onedrive experience. My onedrive app uploads the pictures, with the video and all, a binary copy.

But now that you've mentioned that the windows photo app has google motion enabled.. it doesn't think any of my photos are motion enabled.. I'll have to research their app a bit.

Thanks very much.
