### ISSUE TITLE
Feature request: Native program for GNU/Linux

### ISSUE THREAD

**Issue by cliveontoast** [cliveontoast/GoMoPho#4]
_Originally posted by @augustseptember in https://github.com/cliveontoast/GoMoPho/issues/2#issuecomment-438441641_

**Comment by ghost** [comment]
Thank you very much for your work. I am not into coding, so I don't know how you managed it, but it is very nice, that you don't have to install NET packages anymore.

**Comment by cliveontoast** [comment]
Thanks for the feedback augustseptember. Your contributions are helping me make a better product.

Native binaries are now available for Windows, GNU/Linux, and macOS. They contain .. what looks like is the whole .NET Core system, so they're 25MB zip files, compared to the CrossPlatform version at 0.5MB.
