### ISSUE TITLE
Making GoMoPhoCoreConsole executable

### ISSUE THREAD

**Issue by ghost** [cliveontoast/GoMoPho#5]
In version 1.3alpha i had to make the file _netcoreapp2.0/ubuntu-x64/publish/GoMoPhoCoreConsole_ executable (via `chmod a+x netcoreapp2.0/ubuntu-x64/publish/GoMoPhoCoreConsole` )
And start the program under Ubuntu using `./netcoreapp2.0/ubuntu-x64/publish/GoMoPhoCoreConsole` not `bin/netcoreapp2.0/ubuntu-x64/publish/GoMoPhoCoreConsole`

**Comment by cliveontoast** [comment]
Thanks for the issue augustseptember.

Google, superuser and stacktrace are telling me that it is a difficult problem to solve.
https://stackoverflow.com/questions/13185364/how-to-assign-execute-permission-to-a-sh-file-in-windows-to-be-executed-in-linu

My thoughts are for me to try the linux subsystems in windows 10.

**Comment by cliveontoast** [comment]
Could you try running the following to unzip the program?
```
unzip GoMoPho.Ubuntu.1.3.zip && source grant_perms.sh
```
This is the suggestion from https://stackoverflow.com/questions/13185364/how-to-assign-execute-permission-to-a-sh-file-in-windows-to-be-executed-in-linu

**Comment by cliveontoast** [comment]
I've modified the README.md and readme.txt files with the correct instructions in v1.3.1, that have been tested on Linux Mint 19 "Tara" - MATE (64-bit)
