### ISSUE TITLE
Feature request: Remove the video part from the JPEG file

### ISSUE THREAD

**Issue by slaout** [cliveontoast/GoMoPho#6]
Hello,

Thanks very much for this wonderful program.
It should have been provided by Google!

Is it possible to add a boolean option to "split" the JPEG file:

* First extract the MP4 video in its own file
* Then truncate the original JPEG file to only contain... well... the JPEG part

Would help not having duplicate data, and keep disk usage small.

Best regards,
Sébastien Laoût.

**Comment by cliveontoast** [comment]
Hi Sébastien, good to hear from you. I like your idea. Would you prefer to have a second directory where the results all go? I'm a little reluctant to replace the original. Not doubting my program, it's just I feel funny overwriting the original file.

**Comment by slaout** [comment]
Of course, we can provide a directory as an argument (or by default create a sub-directory named "splitted" or anything else) in which the splitted files will be stored: {originalFileName}.mp4 and {originalFileName}.jpg ...

**Comment by cliveontoast** [comment]
Sorry for the long delay slaout, this feature has been implemented now.
https://github.com/cliveontoast/GoMoPho/releases/tag/v2.0.1

The following command line arguments can be passed to split the jpeg files found in c:\temp\New Folder into two files, a jpg and mp4, with the resulting files written to c:\temp\Processed.
```
.\GoMoPhoConsole.exe d "c:\temp\New Folder" s "c:\temp\Processed"
```

You can also optionally pass the arguments to try processing any jpg files in the source folder
```
p *.jpg
```
