### ISSUE TITLE
"Did Not Find Video" : the return

### ISSUE THREAD

**Issue by webvan1999** [cliveontoast/GoMoPho#7]
I know this has been brought up before but I'm also getting "Did Not Find Video".
The video is there though because I reuploaded to Google Photos and after some processing time it does display correctly. I've attached a file, thanks !
![MVIMG_20190508_151047](https://user-images.githubusercontent.com/30503824/57527311-9f03e300-732f-11e9-8c0b-edd92dca4344.jpg)

**Comment by cliveontoast** [comment]
Hi webvas1999,

I have to appologise for the time it has taken to reply. When I saved the file to my computer, and provided the name of the file name had "MVIMG_" in it, then it was processed successfully.

When you copied the photos to your computer what are the file names?

The quick fix for you is to change the following value in the .config file (either GoMoPhoCoreConsole.dll.config or GoMoPhoConsole.exe.config ) changing the following line:

`    <add key="FilePattern" value="*MVIMG_*.jpg"/>`

to have a different text instead of `*MVIMG_*.jpg`

Otherwise I can expand on the file patterns to search for, either just expand it out to *.jpg

**Comment by juande30** [comment]
Hi Clive, how are you? (sorry for any mistakes, english is not my primary language)

Thanks for writing this!! I'm having a problem though 😢 

I've tried the app (GoMoPhoConsole.exe) and this happens (first image is the example downloaded from here). The other files "move" on Google Photos but the mp4 part is not recognized by the app, i tried with various pics without any succses. 
picture atached  ![MVIMG_20190525_115703](https://user-images.githubusercontent.com/51338003/63214921-3928b380-c0f5-11e9-95f7-926db2bf55a3.jpg)

Let me know if there is anything I can do to help you
Greetings from Argentina!

"
(...)
You can 1) type (or paste) in a folder now - without quotes and press <ENTER>
        2) press <ENTER> to exit


    Example typed text, afterwards pressing <ENTER>
    >c:\somewhere with spaces

> C:\Users\User\Documents\Fotos\Moving Pictures
Found the following number of google motion photos: 5
Searching C:\Users\User\Documents\Fotos\Moving Pictures\MVIMG_20180910_124410.jpg   Found the video
Searching C:\Users\User\Documents\Fotos\Moving Pictures\MVIMG_20190525_115703.jpg   Did not find video
Searching C:\Users\User\Documents\Fotos\Moving Pictures\MVIMG_20190709_171548.jpg   Did not find video
Searching C:\Users\User\Documents\Fotos\Moving Pictures\MVIMG_20190709_171551.jpg   Did not find video
Searching C:\Users\User\Documents\Fotos\Moving Pictures\MVIMG_20190816_173000.jpg   Did not find video
Finished. Processed 5 videos for 5 images files.
Press any key to exit

"

**Comment by cliveontoast** [comment]
Hi juande30,

I'm really pleased that you've found my application. This weekend I've got a new version available. Tomorrow I will look at your sample images to work out what is going wrong.

**Comment by cliveontoast** [comment]
Hi juande30,

I've released a new version ( https://github.com/cliveontoast/GoMoPho/releases/tag/v2.0.1 ), and it does happily process your cat photo. I've attached the results.

[juande30_a.zip](https://github.com/cliveontoast/GoMoPho/files/3563184/juande30_a.zip)

Could you provide the other photos that didn't work in your example?
If the files are not MVIMG files anymore you can still have them processed with the following arguments.
```
.\GoMoPhoConsole.exe d "C:\Users\User\Documents\Fotos\Moving Pictures\" p *.jpg
```

**Comment by juande30** [comment]
Hi Clive, thanks for writing a new version, it worked with my images. I'm also providing the images I could't process. 

![MVIMG_20190709_171548](https://user-images.githubusercontent.com/51338003/64077594-4d011780-cca8-11e9-8255-dd161425a84f.jpg)
![MVIMG_20190709_171551](https://user-images.githubusercontent.com/51338003/64077599-58544300-cca8-11e9-93d4-9ce336d26493.jpg)
![MVIMG_20190816_173000](https://user-images.githubusercontent.com/51338003/64077629-93ef0d00-cca8-11e9-9739-ca67bc9b5b3e.jpg)

I found an issue with the GIF exporter so im making a new thread hahaha.
Again thank you very much for this, if there is anything I can help you just ask.
