### ISSUE TITLE
Gif feature not working

### ISSUE THREAD

**Issue by juande30** [cliveontoast/GoMoPho#8]
Hi Clive, first of all, thanks for writing this soft! 
with the new version 2.0.2 I can export the images and videos from the MVIMG. 
I tried the gif export feature but i couldn't make it work. I think is not a necesary feature, but is fun hahaha. 
Here is the text out from the console. (the pictures are the same i used with the other issue)

Tell me if there's anything i can do to help.

`
PS C:\Users\User\Documents\Fotos\Moving Pictures\GoMoPho.Windows.2.0.2> .\GoMoPhoConsole.exe d "C:/Users/User/Documents/Fotos/Moving Pictures/pruebas" s "Output/" g
Welcome to google motion photos extractor.
If you provide a folder that contains google motion photos,
then I will extract any videos found
Found the following number of google motion photos: 4
Searching C:/Users/User/Documents/Fotos/Moving Pictures/pruebas\MVIMG_20190525_115703.jpg   Found the video
Searching C:/Users/User/Documents/Fotos/Moving Pictures/pruebas\MVIMG_20190709_171548.jpg   Found the video
Searching C:/Users/User/Documents/Fotos/Moving Pictures/pruebas\MVIMG_20190709_171551.jpg   Found the video
Searching C:/Users/User/Documents/Fotos/Moving Pictures/pruebas\MVIMG_20190816_173000.jpg   Found the video
Finished. Processed 4 files, found 4 videos for 4 images files.
Find 4 files to convert to gif
Writing to C:\Users\User\Documents\Fotos\Moving Pictures\GoMoPho.Windows.2.0.2\Output\MVIMG_20190525_115703.gif
Getting FFMpeg, storing C:\Users\User\AppData\Local\FFmpeg
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at GoMoPhoCoreConsole.FFmpegGif.CreateGifs(ConcurrentQueue`1 filesToConvert)
   at GoMoPhoConsole.Program.Run(String[] args) in C:\Users\Clive\Source\repos\GoMoPho\src\GoMoPhoFrameworkConsole\Program.cs:line 73
   at GoMoPhoConsole.Program.Main(String[] args) in C:\Users\Clive\Source\repos\GoMoPho\src\GoMoPhoFrameworkConsole\Program.cs:line 20

One or more errors occurred.
Report to https://github.com/cliveontoast/GoMoPho/issues
`

Thank you!

**Comment by cliveontoast** [comment]
Hi Juan,

Thanks for the very prompt testing of the gif function.
Please try https://github.com/cliveontoast/GoMoPho/releases/tag/v2.0.3

Looking at your log, I think the problem was where I was writing the FFmpeg (gif converter) to. Unfortunately I didn't have my error logging set up properly to fully diagnose the issue. That's been fixed!

I've made a change to write to c:\Users\User\AppData\Local\Temp\FFmpeg instead of previously c:\Users\User\AppData\Local\FFmpeg

**Comment by juande30** [comment]
So, i downloaded de v2.0.3 but the zip file is missing the folowing files (compared to v2.0.3):
- GoMoPhoConsole.exe
- GoMoPhoConsole.exe.config
- GoMoPhoConsole.pdb
I copied the v2.0.2 exe, config and pdb but without succses.

I also downloaded the cross platform but I didn't understood how to make it run

**Comment by cliveontoast** [comment]
Hi Juan,

Thanks for doing this debugging for me. I've resolved the issue. New version!
https://github.com/cliveontoast/GoMoPho/releases/download/v2.0.4/GoMoPho.Windows.2.0.4.zip

Lets hope it's the last one you'll need :)

**Comment by jonmop14** [comment]
@cliveontoast Thank you so much for the quick response. Removing the backslash after "Output"did the trick, this is excellent.  I did notice I had the wrong directory once I sent the image and tried to comment that it also didnt work with the correct one but that doesnt matter.

Quick follow on question regarding file sizes. The main reason i wanted to split was to reduce the file size of the MVIMG jpg and I dont need the gif or mp4 piece.  I tested with 2  MVIMG and here were the results:

![Results](https://user-images.githubusercontent.com/59620208/72077854-f8a91c80-32c5-11ea-9cd1-c9824caf5cdb.jpg)

Would you have expected the 9MB picture to be reduced more than 2MB? 

Regardless, this is a huge improvement and I can delete the gif and mp4 pieces so THANK YOU again.
